name: Deploy Scraper

on:
  push:
    branches: master
    paths-ignore:
      - 'addon/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Create Docker image
        run: |
          docker build -t torrentio-scraper:latest .
          docker save torrentio-scraper:latest > torrentio_scraper_latest.tar

      - name: Upload Docker image
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SCRAPER_SSH_HOST }}
          username: ${{ secrets.SCRAPER_SSH_USERNAME }}
          port: ${{ secrets.SCRAPER_SSH_PORT }}
          key: ${{ secrets.SCRAPER_SSH_KEY }}
          source: torrentio_scraper_latest.tar
          target: /tmp/docker
          overwrite: true

      - name: Deploy Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SCRAPER_SSH_HOST }}
          username: ${{ secrets.SCRAPER_SSH_USERNAME }}
          port: ${{ secrets.SCRAPER_SSH_PORT }}
          key: ${{ secrets.SCRAPER_SSH_KEY }}
          script: |
            docker load -i /tmp/docker/torrentio_scraper_latest.tar
            docker stop torrentio-scraper
            docker rm torrentio-scraper
            docker run -p 80:7000 -d --name torrentio-scraper --restart always -e MONGODB_URI=${{ secrets.SCRAPER_MONGODB_URI }} -e DATABASE_URI=${{ secrets.DATABASE_URI }} -e ENABLE_SCHEDULING=true -e PROXY_HOST=${{ secrets.SCRAPER_PROXY_HOST }} -e PROXY_TYPE=${{ secrets.SCRAPER_PROXY_TYPE }} torrentio-scraper:latest
            docker image prune -f
